const ProfileData = {
    firstName: "John",
    middleName: "Jacob",
    lastName: "Doe",
    email: "jdoe@mail.roanoke.edu",
    phone: "123-456-7890",
    id: "123456789",
    profileImage: 'https://fakeface.rest/thumb/view?gender=male&minimum_age=18&maximum_age=40',
    fullName: function() {return this.firstName + " " + this.middleName + " " + this.lastName;},
    displayName: function() {return this.firstName + " " + this.lastName;},
    mailboxNumber: "1234",
    mailboxUnlockCode: "12-34-56",
    packageArrivedDate: new Date("2023-04-20 12:00:01"), // if not empty/null then a package has arrived
    onCampus: true,
    dormRoomLocation: "Trexler 123",
    hasParkingPermit: true,
    hasMealPlan: true,
    mealPlan: 20,
    mealPlanBalance: 6,
    moneyBalance: 16.03,
    printAllowance: 50,
    printBalance: 48.52,
    cumulativeGPA: 3.759,
    majorGPA: 4.000,
    overallProgress: 0.42,
    totalUnits: 25.5 / 33.5,
    totalUnitsFromSchool: 21.5 / 33,
    attemptedCredits: 18.50,
    completedCredits: 17.50,
    paceOfCompletion: 94.59,
    terms: [
	{id: 1, title: "Fall 2020", grades: [
		{id: 1, title: "CPSC120", midterm: "A", final: "A"},
		{id: 2, title: "STAT210", midterm: "A", final: "A"},
		{id: 3, title: "HNRS110", midterm: "B", final: "A-"},
		{id: 4, title: "HNRS111", midterm: "P", final: "P"},
		{id: 5, title: "CJUS213", midterm: "A", final: "A-"}
	], gpa: 3.850},
	{id: 2, title: "Spring 2021", grades: [
		{id: 1, title: "CPSC170", midterm: "A", final: "B"},
		{id: 2, title: "CPSC170L", midterm: "Z", final: "Z"},
		{id: 3, title: "HNRS112", midterm: "P", final: "P"},
		{id: 4, title: "HNRS120", midterm: "A", final: "A-"},
		{id: 5, title: "HNRS270G", midterm: "A", final: "A-"},
		{id: 6, title: "MATH131", midterm: "A", final: "A-"},
	], gpa: 3.525},
	{id: 3, title: "Fall 2021", grades: [
		{id: 1, title: "CPSC250", midterm: "", final: "W"},
		{id: 2, title: "CPSC250L", midterm: "", final: "Z"},
		{id: 3, title: "CPSC361", midterm: "B", final: "A-"},
		{id: 4, title: "HNRS113", midterm: "P", final: "P"},
		{id: 5, title: "HNRS271", midterm: "A", final: "A"},
		{id: 6, title: "LATN101", midterm: "A", final: "A"},
	], gpa: 3.900},
	{id: 4, title: "Spring 2022", grades: [
		{id: 1, title: "DATA170", midterm: "A", final: "A"},
		{id: 2, title: "HNRS114", midterm: "P", final: "P"},
		{id: 3, title: "LATN102", midterm: "A", final: "A-"},
		{id: 4, title: "MATH268", midterm: "C", final: "P"},
		{id: 5, title: "STAT220", midterm: "A", final: "A-"},
	], gpa: 3.800},
	{id: 5, title: "Fall 2022", grades: [
		{id: 1, title: "CPSC250", midterm: "B", final: "A"},
		{id: 2, title: "CPSC250L", midterm: "Z", final: "Z"},
		{id: 3, title: "CPSC350", midterm: "A", final: "B"},
		{id: 4, title: "CPSC362", midterm: "C", final: "A"},
		{id: 5, title: "LATN201", midterm: "A", final: "A-"},
	], gpa: 3.675},
	{id: 6, title: "Spring 2023", grades: [
		{id: 1, title: "CPSC270", midterm: "A", final: ""},
		{id: 2, title: "CPSC370", midterm: "B", final: ""},
		{id: 3, title: "CPSC464", midterm: "A", final: ""},
		{id: 4, title: "HNRS260PS", midterm: "B", final: ""},
		{id: 5, title: "INQ260AN", midterm: "A", final: ""},
	], gpa: ""},
	{id: 7, title: "Fall 2023", grades: [
		{id: 1, title: "CPSC450", midterm: "", final: ""},
		{id: 2, title: "HHP160", midterm: "", final: ""},
		{id: 3, title: "INQ250CH", midterm: "", final: ""},
		{id: 4, title: "INQ250CHL", midterm: "", final: ""},
		{id: 5, title: "MATH201", midterm: "", final: ""},
	], gpa: ""},
	{id: 8, title: "Spring 2024", grades: [
		{id: 1, title: "CPSC470", midterm: "", final: ""},
		{id: 2, title: "HHP114", midterm: "", final: ""},
		{id: 3, title: "INQ300", midterm: "", final: ""},
		{id: 4, title: "MATH122", midterm: "", final: ""},
	], gpa: ""},
    ],
}

export default ProfileData;