name: Expo Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  NODE_VERSION: 20.x

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        token: ${{ secrets.EXPO_CLI_TOKEN }}
        packager: 'npm'
        eas-version: latest
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      id: test
      run: npm test